Latest changes.

diff --git a/.local/bin/synchome b/.local/bin/synchome
--- a/.local/bin/synchome
+++ b/.local/bin/synchome
@@ -1,15 +1,24 @@
 #!/bin/sh
 
-if [ -z "$1" ]; then
+function help {
 
     echo "Usage: $(basename $0) [sshservername|directory]"
+    
+}
+
+if [ -z "$1" ]; then
+
+    help
 
     exit 1  
+
 fi
 
 if ssh -q $1 sh -c 'exit'; then
 
-    if rsync -HaPr --ignore-missing-args --delete --timeout=60 --exclude-from ~/.config/rsync/exclude-home --files-from ~/.config/rsync/from-home ~ "$1:"; then
+    if rsync -HaPr --delete --timeout=60 --exclude-from ~/.config/rsync/exclude-home --files-from ~/.config/rsync/from-home ~ "$1:"; then
+
+        ssh $1 chmod 640 ~/.local/bin/dose ~/.local/bin/wf ~/.local/bin/bp        
 
         exit 0
 
@@ -19,19 +28,25 @@ if ssh -q $1 sh -c 'exit'; then
 
     fi
 
-    ssh $1 chmod 640 bin/dose bin/wf bin/ud
-
 fi
 
-if [ "$1" = "${1#/}" ]; then
 
-    echo "Error: target directory $1 must be an absolute path."
+# if [ "$1" = "${1#/}" ]; then
+# dirname=$(dirname $1)
 
-    exit 1
+# if ! test -w $dirname; then
 
-fi
+#     # echo -e "\nError: target directory '$1' must be an absolute path.\n" &> /dev/stderr
+#     echo -e "\nError: target directory '$dirname' is not writeable.\n" &> /dev/stderr
+
+#     help
+
+#     exit 1
+
+# fi
+
  
-if rsync -HaPr --ignore-missing-args --delete --timeout=60 --exclude-from ~/.config/rsync/exclude-home --files-from ~/.config/rsync/from-home ~ "$1"; then
+if rsync -HaPr --delete --timeout=60 --exclude-from ~/.config/rsync/exclude-home --files-from ~/.config/rsync/from-home ~ "$1"; then
 
     exit 0
 
